#!/usr/bin/env python
import sys
if len(sys.argv) != 2:
    print "Usage: %s <circuit.v> > output.v" % (sys.argv[0])
    sys.exit(0)
filename = sys.argv[1]
f = open(filename, 'r')
tokens = []
for line in f:
    line = line.translate(None, '\n').replace(",", "")
    for t in line.split(" "):
        if len(t) > 0:
            tokens.append(t)
i = 0
if tokens[i] == 'module':
    print 'module %s (' % tokens[i+1]
    i = i + 3
    while tokens[i] != ');':
        if tokens[i + 1]  != ');':
            print '%s,' % tokens[i]
        else:
            print '%s' % tokens[i]
        i = i + 1
    print ');'
    i = i + 1
    print '\n// Start PIs'
    if tokens[i] == 'input':
        i = i + 1
        while tokens[i] != 'output':
            if tokens[i][-1] != ';':
                print 'input %s;' % tokens[i]
            else:
                print 'input %s' % tokens[i]
            i = i + 1
    print '\n// Start POs'
    if tokens[i] == 'output':
        i = i + 1
        while tokens[i] != 'wire':
            if tokens[i][-1] != ';':
                print 'output %s;' % tokens[i]
            else:
                print 'output %s' % tokens[i]
            i = i + 1
            
    print '\n// Start wires'
    if tokens[i] == 'wire':
        i = i + 1
        while tokens[i-1][-1] != ';':
            if tokens[i][-1] != ';':
                print 'wire %s;' % tokens[i]
            else:
                print 'wire %s' % tokens[i]
            i = i + 1
    
    print '\n// Start cells'
    while tokens[i] != 'endmodule':
        j = 0
        while tokens[i] != ');':
            if j > 2 and tokens[i+1] != ');':
                print "%s," % tokens[i],
            else:
                print "%s" % tokens[i],
            i = i + 1
            j = j + 1
        print ');'
        i = i + 1
    print '\nendmodule'
